from src.benchmark.logic_synthesis.blif_parser.blif import BlifFile
from src.gp.problem import Problem
from src.gp.tinyverse import GPModel, Var
from src.gp.tinyverse import Var

from dd.autoref import BDD, Function #Python implementation of BDD
if not hasattr(Function, '__xor__'):
    Function.__xor__ = lambda self, other: self._apply('xor', other)
else:
    try:
        from dd.cudd import BDD, Function  #CUDD implementation of BDD
        assert hasattr(Function, '__xor__')
    except:
        pass

from src.gp.tinyverse import Function

AND = Function(2, 'AND', lambda x, y: x & y)
OR = Function(2, 'OR', lambda x, y: x | y)
NOT = Function(1, 'NOT', lambda x: ~x)
NAND = Function(2, 'NAND', lambda x, y: ~(x & y))
NOR = Function(2, 'NOR', lambda x, y: ~(x | y))
XOR = Function(2, 'XOR', lambda x, y: x ^ y)
XNOR = Function(2, 'XNOR', lambda x, y: ~(x ^ y))
ID = Function(1, 'ID', lambda x: x)

class BlackBoxBDD(Problem):
    '''
    A black-box LS problem where the fitness is calculated by a loss function
    using a BDD representation.

    @param blif_: The reference circuit (problem specification) in BLIF file.
    @param minimizing_: Whether the problem is minimizing or maximizing.
    '''
    def __init__(self, blif_: str, minimizing_: bool = True, debug_: bool = False):
        self.blif = blif_
        self.minimizing = minimizing_
        self.ideal = 0

        known_blif_gates = ["INVA", "IDA", "AND2", "OR2", "XOR2", "NAND2", "NOR2", "XNOR2"]

        b = BlifFile(known_gates=known_blif_gates)
        self.num_inputs, self.num_outputs, gates = b.parse(blif_)

        self.bdd = BDD()

        vars = [g for g in b.eachInput()]
        self.input_variables = vars
        self.terminals_ = [Var(None, name_=n) for i, n in enumerate(vars)]
        self.bdd.declare(*vars)

        g2v = {}
        self.bdd_vars = []
        for g in b.eachInput():
            v = self.bdd.var(g)
            g2v[g] = v
            self.bdd_vars.append(v)

        for g in b.eachGate():
            if debug_: print(g, g.name, g.ina, g.inb, g.arity(), known_blif_gates[g.fun], end=' ')

            ina = g2v[g.ina] if g.ina else None
            inb = g2v[g.inb] if g.inb else None

            match known_blif_gates[g.fun]:
                case 'AND2':
                    o = ina & inb
                case 'OR2':
                    o = ina | inb
                case 'XOR2':
                    o = ina ^ inb
                case 'NAND2':
                    o = ~(ina & inb)
                case 'NOR2':
                    o = ~(ina | inb)
                case 'XNOR2':
                    o = ~(ina ^ inb)
                case 'INVA':
                    o = ~ina
                case 'IDA':
                    o = ina
            g2v[g.name] = o
            if debug_: print(o)

        self.reference = []
        for o in b.eachOutput():
            if debug_: print('output', o, g2v[o])
            self.reference.append(g2v[o])
       
    @property
    def terminals(self):
        return self.terminals_
    
    def evaluate(self, genome, model: GPModel) -> float:
        """
        Determine the Hamming distance between the predicted and the reference circuit.
        The predicted circuit is generated by the model using the genome and the
        BDD variables.
        The reference circuit is the BDD representation of the problem specification.
        """
        prediction = model.predict_iter(genome, self.bdd_vars)
        hd = 0
        for i in range(self.num_outputs):
            odiff = self.bdd.apply('xor', prediction[i], self.reference[i])
            #odiff = prediction[i] ^ self.reference[i]
            hd += odiff.count()
        return hd
